### PR TITLE
Replaced 'destructor' with IDispose in StreamOutlet

### PR DESCRIPTION
**Pull request by GrahamBriggs**
Relying on destructor does not work in garbage collection environment. The stream outlet will remain open until garbage collection takes care of it for you.  This is random and non deterministic, so your outlet will remain open long after you want it gone.

Use IDisposable gives you explicit control over the outlet destruction.  You may now wrap the outlet in a using statement to control when it is destroyed.

example

 using (var outlet = new liblsl.StreamOutlet(StreamInfo))
{
}  //  Outlet is always destroyed after this closing bracket goes out of scope, giving you the control you need over when the outlet gets closed.

### CODE REVIEW

**Comment by GrahamBriggs** [comment]
Oops, did not understand fully myself, Class should have both IDispose and destructor.  Will go back and redo

**Comment by GrahamBriggs** [comment]
Implemented Dispose pattern as described by microsoft according to the doc here: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by dmedine** [comment]
I am currently working on a C# project that uses LSL, so I am happy to review this.

Actually, I encountered this same problem and was thinking of making this very change myself so the timing is excellent. From a first glanced it looks quite correct, but I will play around with it to make sure.

I do have some notes. The first is that the using directive on line 3 should be deleted. Always run ctl-k ctl-d to remove unused using directives. Also, the white space needs to be consistent. Some function/class definitions have 1 space in between, some have 2. It should always be 1, except in the case of wads of overloads such as pull_sample which can be bunched together. Blocks of member variables should be at the top of a class definition, followed by properties (I don't think there are any in LSL.cs), then public methods, then private methods. Each section (member variables, properties, public methods, private methods, etc.) should be encased with the #region ... #endregion directions to make the code collapsable. I didn't see any examples, but just in case, member variables should not have whitespace, but blocks of members should be separated from functions with one space. Finally, the comments use the wrong style. They should be re-written using the '///' convention which visual studio will auto-format for you. I would be happy to re-do the comments and whitespace if you can fix up the white space and remove using System.Collections;. I realize this has nothing to do with your PR and goes back to the original iteration of the wrapper so it isn't right to ask you to do a bunch of work fixing it up. However, if you want to handle some of this, I am by no means opposed ;-).

This change also means that the C# wrapper will also need versioning to distinguish it from the non IDispoposable implementing version.

And while I'm on the subject, and since I always put too many points in issues, I will mention that I would like to change the C# wrapper so that it follows the recommended naming conventions for that language. This means the public function calls should all be camel case instead of using underscores. This is purely cosmetic and it may wreak havoc with LSL for unity, but it looks really bad and sort of 'unprofessional' in a C# environment. Also, since C# is becoming a very important language it is worth putting the effort into keeping this wrapper tip-top.

This also mean preceding any member variable with a '_'. This only applies to private members so this wouldn't break anything. If I understand correctly, in C# all member variables should be private and one should use properties to access them, but this doesn't apply to LSL.

Comments?

**Comment by GrahamBriggs** [comment]
David

Thank you for taking the time to review.

Regarding unused using directive. I did not put that in there, so I did think I should remove it. I wanted to submit minimal changes to the source file so it was easier for the maintainers to review.

Same thing goes for running auto format. If you run auto formatting, you will change so many lines of the code that it becomes more difficult to review it.

I noticed that formatting was not terribly consistent to begin with, and the indentation was fighting visual studio default auto formatting all the way, so I made my code changes as concise and localized as possible.

Please do review my changes. These days I am a part time hack, and the bulk of my programming experience is in C++, so I am by no means an expert on disposal or garbage collection.

FWIW:  I have been running with these changes in my project all day and everything is smooth. It solved my immediate problem of closing LSL outlet when I expected it to be closed, and has not caused any collateral damage.  I did some debugging and set some break points in the destructor function to ensure that garbage collection destruction was happening for the objects when the code does not explicitly call Dispose or wrap in using( ), and I also did some testing watching the memory usage of the program and everything looks good.  I am running this code on Windows, Android using Xamarin, and Raspberry Pi (Raspbian linux) using Mono.

My $0.02 regarding renaming functions in the wrapper.  I would not recommend to do this for the following reason. The documentation and the lion's share of the samples are written against the C API function names. It is much easier to follow samples or to rewrite in C# from someone's python or java implementation when all the function names can be cut and paste.  Small thing for sure, but from my perspective if the library is a wrapper for C code, I kind of prefer to have the functions named exactly as they appear in documentation and native code samples.

Thanks again

**Comment by dmedine** [comment]
You were right not to change what was not part of your enhancement, and in fact, cleaning up the wrapper should be a separate issue. I just got a little carried away. I will do this after we merge your changes.

Thanks for your comments about the renaming issue. I am of two minds about it. It poses many problems for a cosmetic fix, but C# tries to be quite strict about this things and in the end it does pay off quite a bit in terms of code readability.

It should also be the case that if the disposing is implemented correctly that it should work equally well on any device with .NET installed. Which reminds me that another thing that should be changed is that the project should target .NET Core 3.1, not .NET Framework 2.0.

**Comment by cboulay** [comment]
Hi @GrahamBriggs , thank you very much for this PR.

The LSL.cs file has been touched by several hands over the years. Not everyone uses visual studio. Not everyone has the same settings, etc. So please be forgiving of the white space and comment formatting. Any changes to those things are welcome, but in a separate PR.

On that note, there's currently a conflict with this PR, probably because you based your changes off a version of LSL.cs that was more than 6 days old, when @tstenner redid the formatting and added an .editorconfig file, I guess to address exactly the formatting issues. If it's not too much trouble, could you please rebase your changes on the latest HEAD? For your reference, you can more easily see your changes by comparing to the previous commit [at this link](https://github.com/labstreaminglayer/liblsl-Csharp/compare/de1f93a583aecc1e1669ef38431bf61fc26f46bf...GrahamBriggs:StreamOutlet_Disposable).

@dmedine - Please don't change the function names. Most LSL.cs users are using Unity and some are more capable than others at handling such an update. And I don't want to have a separate LSL.cs for Unity and general C#; we had that before and it led to some users using an outdated file, creating support headaches.

**Comment by dmedine** [comment]
Hmmm... I seem to remember a certain contributor complaining mightily that pylsl wasn't 'pythonic' enough once upon a time (although to be fair, the changes did not require changing function names). 

This is indeed a separate issue, so we can shelve this issue for now.

**Comment by dmedine** [comment]
The fact remains, though, that this update requires versioning. Changing the behavior of the garbage collector behind the scenes is a major change to how this software works. It will result in support cases and it is now necessary to ask people which version they are using.

**Comment by cboulay** [comment]
@dmedine Good idea re versioning. I guess it needs to be done before merging this PR.

Previously we've been numbering the language wrappers with the same numbering scheme as the core liblsl they were wrapping, and typically only updating modifying the .PATCH value. This hasn't been a rule by any means and I suppose other conventions could be used.

I don't know C# conventions nearly as well as you do so please do whatever makes sense to you, whether that's putting the version number at the top of LSL.cs or in a specific file. In any case, after making that commit, you should probably also do a `git tag -a v1.14.3` (or whatever number) and make sure you either have your git push configured to follow-tags or push the tag separately.

**Comment by tstenner** [comment]
> This is purely cosmetic and it may wreak havoc with LSL for unity, but it looks really bad

Counterpoint: This is purely cosmetic and it will wreak havoc with LSL for unity and all other existing users of the wrapper.

> Which reminds me that another thing that should be changed is that the project should target .NET Core 3.1, not .NET Framework 2.0.

Did they finally make it possible to use .NET Standard 2.1 with .NET Framework 4.8? If not, there's no real use (yet) to upgrade.

**Comment by dmedine** [comment]
Ah yes, it is .NET Standard isn't it.

Is this a Unity thing? My understanding is that basically everything should move to Core as it is the future of .NET. However, a lot of the different stuff in the newer versions (like advanced async stuff, IObservable etc.) isn't needed in this simple wrapper.

**Comment by dmedine** [comment]
@cboulay, I think the version convention can be followed as you suggest. It makes a lot of sense to me. What I can do is push a get_csharp_version() (sigh) method into the OP's PR. Also, I think we can straight force the merge without fear. Otherwise, I will wait for Graham to rebase, then add the version commit. In the meantime, we should publish a 'legacy' release so that it is there.

I will then get to work on the other issues, leaving the incorrectly titled method names alone.

**Comment by tstenner** [comment]
> Is this a Unity thing?

No, .NET Standard is a subset of .NET Framework and .NET Core, at least until .NET Standard 2.1 where it dropped .NET Framework compatibility, and it's totally different from plain .NET without Core + Framework. It's the same logic as with Windows versioning (3.11-> {NT 4.0, 2000} / {95->98->ME} -> XP->Vista->7->8->10), just with .NET Framework 2.0-4.0 -> .NET Core 1-3.1 -> .NET 5 with .NET Standard inbetween.

> `get_csharp_version()`

Yay, runtime errors. Why don't we just rename `liblsl` to `LSL` so the name has to be changed in client code and sprinkled with `using` while they're at it?

Also, we haven't published a single Nuget package so we might get all our changes in before it gets official.

**Comment by dmedine** [comment]
> Yay, runtime errors. Why don't we just rename liblsl to LSL so the name has to be changed in client code and sprinkled with using while they're at it?

I thought we were in the business of protecting clients from ever having to upgrade anything ;-). It's in the namespace so a generic and perhaps oft used method name shouldn't matter --- or am I misunderstanding you?

**Comment by tstenner** [comment]
> I thought we were in the business of protecting clients from ever having to upgrade anything ;-). It's in the namespace so a generic and perhaps oft used method name shouldn't matter --- or am I misunderstanding you?

They shouldn't *need to* change anything, unless there's a good reason. Implementing `IDisposable` is a good idea and I don't know why it hasn't been in there from the beginning. It will require some changes in client code, so we might as well rename the class so all usages of the class are inspected and converted to `using var lsl=LSL…`.

**Comment by GrahamBriggs** [comment]
I have deleted this branch and closed this request. I have created a new pull request implemented from the tip of the current master. Please see new pull request

**Pull request closed without merging**
